# Generated by Django 6.0.3 on 2026-04-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actores', '0001_initial'),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('En Curso', 'En Curso'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Desertó', 'Desertó')], default='En Curso', max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cursos', to='actores.docente')),
            ],
        ),
        migrations.CreateModel(
            name='NecesidadCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brecha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prioridad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Plan', 'Asignada a un Plan'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='evaluaciones.criterioevaluacion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necesidades', to='actores.docente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('diagnostico_ia', models.TextField(blank=True, null=True)),
                ('recomendacion_ia', models.TextField(blank=True, null=True)),
                ('cursos_sugeridos', models.TextField(blank=True, null=True)),
                ('estado_aprobacion', models.CharField(choices=[('Borrador', 'Borrador'), ('Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=20)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_capacitacion', to='actores.docente')),
            ],
        ),
    ]
